# CD Pipeline for Deployment to Azure

trigger:
- none

variables:
  azureSubscription: '241de0d6-a39b-46a4-bd43-5c06fd0a83c3'
  webAppName: 'mycatdogvoting'
  environmentName: 'mycatdogvoting'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Start
  displayName: Start
  jobs:
  - job: StartJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: echo Starting CD Pipeline
      displayName: 'Start CD Pipeline'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Start
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: '
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|10.10'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start'
